### ISSUE TITLE
Development solid export condition

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid-docs-next#391] opened 2023-01-16 20:33 UTC
How should library authors set up export conditions to have separate entries for dev and prod? I'm making a [tsup preset](https://github.com/solidjs-community/tsup-preset-solid) that would automatically configure those when building a library, this is just the last part that isn't working quite right.

This configuration works in the vite templates. `dev.jsx` is loaded in development and `index.jsx` in production when building.
But In solid-start the `dev.jsx` entry is taken in both cases.

Having a separate entry for the server works without issues though.
```json
{
  "solid": {
    "development": "./dist/dev.jsx",
    "import": "./dist/index.jsx"
  },
  "development": {
    "import": {
      "types": "./dist/index.d.ts",
      "default": "./dist/dev.js"
    }
  },
  "import": {
    "types": "./dist/index.d.ts",
    "default": "./dist/index.js"
  }
}
```

**Comment by trusktr** [comment] 2023-12-20 21:11
The Node.js `exports` thing something to avoid (imo) because it is not part of the ES Module standard. I avoid it altogether, and find other means to do dev vs prod (f.e. set env vars, give devs the tools to configure whether their build will compile out the branches or not, but by default leave the branches in and don't shipped multiple formats of the code stripped and non-stripped).

They are not out in Node.js yet, but standard `importmap`s are a lot better because:

1. end app author has full control of dependencies.
   - issues like node module resolution accidentally placing two versions of Solid into a bundle are easy to solve explicitly when using importmaps
   - wrong dist vs prod file being imported is no issue (the app author makes that choice)
   - individual files *inside any package* can be mapped to alternative implementations, etc.
2. import maps will work everywhere, in a standard way (see the [Node.js import maps tracking issue](https://github.com/nodejs/node/issues/49443) which is an important item on the [loaders to-do list](https://github.com/nodejs/loaders#milestone-3-usability-improvements)).
   - when Node comes out with importmaps, they will likely become supported as a standard by all build tools (tools like Webpack, etc, currently understand `exports`, but not import maps)

With import maps, users will be able to opt into dev vs prod in a more explicit way. This will be great because the current automatically-try-to-guess method embedded in the tooling can leave people stuck and feeling out of control when issues like that [one from Chakra](https://github.com/chakra-ui/ark/issues/1363) happen, especially in the many possible use cases for Solid.js outside of components (f.e. server apps, data manipulation, state management libraries, etc, where SSR, loading mock APIs, dev vs prod, etc, may not be concerns and these roadblocks get in the way of doing great things).

Here's a sample of importmap flexibility, where we can override a specific file from a package with another:

https://codepen.io/trusktr/pen/KKEPGYB?editors=1010

Keep an eye out for Node import maps, because this is something we should align with!

In the meantime, besides the above, this this 160-line-long `exports` field _monster_ is a problem (in my opinion):

https://github.com/solidjs/solid/blob/51c94859098170c913c02a0fe1d9003d1664d130/packages/solid/package.json#L46-L206

If I could make the choice, it would be deleted, and Solid would ship vanilla standard ES modules, and then Solid would build the tooling around that instead of around Node.js, making **_Solid easily portable and more interoperable._**

Building around Node.js is locking into non-standard ways of doing things that will not progress forward very well, **_especially_** for a library that is a client-side library, unlike Node.js packages that are intended for Node.js runtime only. The `exports` field is designed specifically for Node.js runtime libraries, and relying on this for a mostly-browser library is just not ideal.

_I highly recommend (highly wish) for Solid.js to become as vanilla as possible, which not only simplifies things for users that want to use Solid.js in any way besides the default way with Solid's default tooling, but will also simplify maintenance._

There _is_ a better way. People have been doing dev vs prod builds (etc) long before Node.js `exports` existed.

The future is libraries that simply work based on standards, without any issues like the Chakra issue, but that have opt-in tooling to achieve what is needed (f.e. prod vs dev, srr vs client, etc).

# The ideal setup, imo

- write branches in source code (ssr vs not, dev vs prod, etc) with default behavior based on runtime env vars (f.e. default to actual runtime without no-opping (not ssr) and default to dev)
- compile TS from `src/` into `dist/` with declarations. Do not ship bundles.
- do not use `exports`
- set the `main` field to `dist/index.js` which is compiled from `src/index.js` (or `dist/solid.js` if the entry is `src/solid.js`, etc)
- set the `types` field to `dist/index.d.ts` (or `dist/solid.d.ts` if the entry was `src/solid.js`, etc)
- publish separate build tooling that takes this simple format and does what it needs to do (f.e. compile conditional branches based on env var)

As far as the library structure, that's it! You are done! Super simple. Benefits:

1. This works everywhere with the most minimal amount of friction. Something like Chakra's issue will never happen.
2. A vanilla ES module client app can write a simple import map to point to where local `solid-js` is installed, and it just works
3. the devtools experience is great with or without source maps (mostly the difference is just stripped types).
4. Just about every single JS ecosystem modern build tool on the planet can import from this structure without failure, without any possible complication
5. Any runtime can easily import from this (Deno, Node, Bun, etc)
6. It is very very easy to go **_buildless_** on both server or client with this setup, with no complications
7. Build tools can be added to achieve dev vs prod, ssr vs not, compile `html` template tags or not (like Lit's [new compiler](https://lit.dev/blog/2023-10-10-lit-3.0/#compiler)), with a 100% opt-in experience beyond the super basic package setup.
8. It will be easier to make more integrations for Solid.js, even in build setups that are not so mainstream, because they don't need to implement all this conditional module lookup algos.
9. Generally speaking, it will just be way easier for any tools in the world to simply consume these files.

If someone from core officially endorses trying out a simpler setup, I will be willing to help prototype it.

**Comment by trusktr** [comment] 2023-12-20 21:50
Here's one of my packages (which as you might guess, follows those ideas):

https://github.com/lume/element

I've committed the `dist/` folder so it is all easy to see from the repo (commiting `dist/` is not on my list of recommendations, but for my needs this makes it easy to clone the `lume` super repo and everything works out of the box with no build, which is something I valued, and makes live vanilla demos like this one possible: https://raw.githack.com/lume/lume/develop/examples/gltf-model.html).

We can see that https://github.com/lume/element/blob/main/src/index.ts maps to https://github.com/lume/element/blob/main/dist/index.js along with sibling source map and declaration files. The same applies to other files.

# Other problems with Solid's setup I forgot to mention above

- Developer intellisense experience is not as good as it can be. With `solid-js`, Go-To-Definition on a Solid API goes to a declaration file, but often we want to look at implementation.
  - Run Go-To-Defintion on a `@lume/element` API and you'll be taken to its source, with comments and everything. Useful for learning.
- In `solid-js` is it not at all clear that a bunch of its code comes from a package called `dom-expressions`. That's because the dom-expressions package is copied into solid-js when building solid-js locally.
  - Solid's final code is far removed from the format of its source, which also makes learning more difficult.
  - Out of the box, due to this bespoke format, developers will not be able to simply Go To Definition to see original source files that might come from dom-expressions.
  - Development of dom-expressions is essentially hidden, outside of the solid-js repo.
- If someone wants to consume a specific piece of Solid.js, wants to import only that piece (for example, `signals.ts`), they cannot.
  - They will need to clone solid-js, and build it, and make a custom pipeline just to consume that.
  - If it were all just plain ESM, it would be super simple to consume a piece of Solid's APIs.
- people cannot easily replace a piece of Solid.js with an alternative implementation (like we can with plain ES and importmaps), they will have to fork Solid.js just to make a custom build of it.


I can think of more. Vanilla ES modules is simply the way to go. Maximal ease, portability, longevity, and interoperability.

---

# Solid 2.0

Let's please 🙏 consider this for Solid 2.0. I see we're already going in the same direction:

https://github.com/solidjs/signals/blob/dcf7521abad59cacce53a881efd5191627cc46c6/package.json#L35C9-L45

**Comment by shiro** [comment] 2023-12-20 22:06
My 2 cents: Yesterday I went to inspect `getRequestEvent`, which took me to a declaration file, which had no reference to `dom-expressions` at all, so I had to go to github and use global search for it in solid start, solid and finally dom-expressions...

Not sure if other IDEs can do it, but at least the current behaviour with the TS language server for vim isn't great (I assume it's similar with other tools). If it's possible to go to the source directly, that would be great, also being able to consume just signals would be cool as well!

**Comment by trusktr** [comment] 2023-12-20 22:11
Yep, it would be nice!

> Not sure if other IDEs can do it

IDEs never will be able to do it because generic IDEs will never be specifically designed to understand Solid's bespoke file copying pipeline. Only an hypothetical IDE made by Solid team could do it.

**Comment by aminya** [comment] 2023-12-20 23:16
> do not use exports

@trusktr I agree with your suggestion to support import maps if someone is interested in using them, but I don't think it is a good idea to break the Nodejs exports. Nodejs has its own standard that many tools support. Breaking the tooling in each new version is a huge mistake that can hinder the adoption of newer versions.

**Comment by trusktr** [comment] 2023-12-21 05:14
If Solid 2.0 may already be an ecosystem breaking change, and all of Solid's prescribed tools that the team manages (f.e. app generators, Solid Start, any plugins for vite/babel/etc), then this change will be for the better.

I.e. a clear migration path should be defined.

Here's just one more example of problem caused by the current setup:

<img width="551" alt="Screenshot 2023-12-20 at 9 06 58 PM" src="https://github.com/solidjs/solid-docs-next/assets/297678/22dc1ce9-273c-4d50-9af5-a2355d4643b6">

Why do I auto-complete? Devs should just see one option: "I just want untrack from solid.js".

**Comment by aminya** [comment] 2023-12-21 07:13
I am all on for improvements and innovation, but I do not consider import maps superior to Nodejs exports. It's just a matter of different standards. Browsers sometimes have fallen behind the innovations of Nodejs, and I do not necessarily think import maps are inherently better. I respect your choice if you're on the team with "browsers and no local tooling", but it should be considered that many people are not, and there are many benefits from other perspectives.

So, a yay for innovation, but a nay for breaking things for the sake of a change.

**Comment by LadyBluenotes** [comment] 2024-02-14 16:56
Consolidated this into #473

**Closed by LadyBluenotes** 2024-02-14 16:56 UTC
Labels: improve documentation, add new content
